apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: core-applications
value: 1000010
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "This priority class should be used for the CHAIMELEON applications that are used by the CHAIMELEON users."