apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: core-services
value: 1000100
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "This priority class should be used for the core service of the CHAIMELEON infrastructure."