
# ORTHANC queda disponible en https://breastscan-node.imaging.i3m.upv.es/orthanc/ui/app/index.html#/
apiVersion: v1
kind: Namespace
metadata:
  name: orthanc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-extra-config
  namespace: orthanc
data:
  prefix.json: |
    {
      "HttpServerPrefix": "/orthanc"
    }
---
#Removed
#"HttpServerPrefix": "/orthanc",
#        "PathPrefix": "/orthanc",
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-config
  namespace: orthanc
data:
  ORTHANC_JSON: |
    {
      "Name": "Breast Scan",
      "RemoteAccessAllowed": true,
      "AuthenticationEnabled": true,
      "HttpServerEnabled": true,
      "HttpPort": 8042,
      "BehindReverseProxy": true,
      "HttpRoot": "/orthanc/",
      "RegisteredUsers": {
        "admin": "admon"
      },
      "Plugins" : [
        "/usr/share/orthanc/plugins/",
        "/usr/share/orthanc/plugins-available/libStorageLink_ChangeCallback.so"
      ],
      "StorageLink" : {
        "LinkDirectory": "/var/lib/orthanc/storage_link/"
      },
      "DicomWeb": {
        "Enable": true,
        "Root": "/dicom-web/"
      },
      "OrthancExplorer2": {
        "Enable": true,
        "Theme": "dark",
        "UiOptions": {
          "EnableUpload": true,
          "EnableDeleteResources": false,
          "EnableAnonymization": false,
          "EnableModification": false,
          "EnableSendTo": false,
          "EnableSettings": false,
          "EnableLinkToLegacyUi": false,
          "EnableEditLabels": false,
          "EnableAddSeries": true,
          "EnableDownloadZip": false,
          "EnableDownloadDicomDir": false,
          "EnableDownloadDicomFile": false
        }
      }
    }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orthanc-storage
spec:
  storageClassName: othanc-datalake
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/hostpath-provisioner/dataset-service/datalake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-storage-pvc
  namespace: orthanc
spec:
  storageClassName: othanc-datalake
  volumeName: pv-orthanc-storage  
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
  namespace: orthanc
  labels:
    app: orthanc
spec:
  replicas: 1 # Standard Orthanc (SQLite) does not support multiple replicas
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      containers:
      - name: orthanc
        image: harbor.eucaim.cancerimage.eu/library/orthanc/orthanc:26.1.0
        #image: orthancteam/orthanc:24.2.0
        ports:
        - containerPort: 8042
          name: http-web
        - containerPort: 4242
          name: dicom
        env:
        - name: ORTHANC_CONFIG
          value: '/etc/orthanc/orthanc.json'
          #        - name: ORTHANC_JSON
          #          valueFrom:
          #            configMapKeyRef:
          #              name: orthanc-config
          #              key: ORTHANC_JSON
        - name: ORTHANC__DICOM_AET
          value: ORTHANC_K8S
        - name: DICOM_WEB_PLUGIN_ENABLED
          value: 'true'
        - name: OHIF_PLUGIN_ENABLED
          value: 'true'
        volumeMounts:
        - name: storage
          mountPath: /var/lib/orthanc
        - name: orthanc-config
          mountPath: /etc/orthanc
            #          mountPath: /etc/orthanc/orthanc.json
            #       subPath: orthanc.json
            #        - name: config-volume
            #          mountPath: /etc/orthanc/prefix.json
            #          subPath: prefix.json
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: orthanc-storage-pvc
          #          claimName: datalake-data
          #namespace: dataset-service
      - name: orthanc-config
        configMap:
          name: orthanc-config
          items:
          - key: ORTHANC_JSON
            path: orthanc.json
            #      - name: config-volume
            #        configMap:
            #          name: orthanc-extra-config
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-service
  namespace: orthanc
spec:
  type: ClusterIP
  selector:
    app: orthanc
  ports:
  - name: web-ui
    protocol: TCP
    port: 80
    targetPort: 8042
  - name: dicom-port
    protocol: TCP
    port: 4242
    targetPort: 4242
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orthanc-ingress
  namespace: orthanc
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: breastscan-node.imaging.i3m.upv.es
    http:
      paths:
      - path: /orthanc(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: orthanc-service
            port:
              number: 8042
orthanc-si-va.yaml
Mostrando orthanc-si-va.yaml.
