apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-extra-config
  namespace: orthanc
data:
  prefix.json: |
    {
      "HttpServerPrefix": "/orthanc"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-config
  namespace: orthanc
data:
  ORTHANC_JSON: |
    {
      "Name": "Breast Scan",
      "RemoteAccessAllowed": true,
      "AuthenticationEnabled": true,
      "HttpServerEnabled": true,
      "HttpPort": 8042,
      "BehindReverseProxy": true,
      "HttpRoot": "/orthanc/",
      "RegisteredUsers": {
        "admin": "admon"
      },
      "StableAge": 5,
      "UserMetadata" : {
       "patientID-encrypted" : 1024
      },
      "LuaScripts": [
        "/var/lib/orthanc/scripts/script.lua"
      ],
      "Plugins" : [
        "/usr/share/orthanc/plugins/",
        "/usr/share/orthanc/plugins-available/libStorageLink_ChangeCallback.so"
      ],
      "StorageLink" : {
        "LinkDirectory": "/var/lib/orthanc/storage_link/"
      },
      "DicomWeb": {
        "Root": "/dicom-web/"
      },
      "OrthancExplorer2": {
        "Theme": "dark",
        "UiOptions": {
          "EnableOidc": true,
          "EnableUpload": true,
          "EnableDeleteResources": false,
          "EnableDownloadZip": false,
          "EnableDownloadDicomDir": false,
          "EnableDownloadDicomFile": false,
          "EnableAnonymization": false,
          "EnableModification": false,
          "EnableSendTo": false,
          "EnableSettings": false,
          "EnableLinkToLegacyUi": false,
          "EnableEditLabels": false,
          "EnableAddSeries": true,
          "EnableApiViewMenu": false,
          "CustomButtons": {}
        }
      }
    }
---
