apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orthanc-ingress
  namespace: dataset-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
spec:
  ingressClassName: nginx
  rules:
    - host: breastscan-node.imaging.i3m.upv.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orthanc-service
                port:
                  name: web-ui
