kind: Deployment
apiVersion: apps/v1
metadata:
  name: fem-client
  namespace: eucaim-fed-computation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fem-client
  template:
    metadata:
      labels:
        app: fem-client
    spec:
      volumes:
        - name: homes
          cephfs:
            monitors:
              - 192.168.10.230:6789
              - 192.168.10.3:6789
              - 192.168.10.4:6789
            path: /homes/users/
            user: fem-client
            secretRef:
              name: ceph-auth
        - name: fem-client-vol
          persistentVolumeClaim:
            claimName: fem-client-pvc
        - name: config-env
          configMap:
            name: fem-client-env
            items:
              - key: .env
                path: .env
            defaultMode: 420
        - name: config
          projected:
            sources:
              - secret:
                  name: fem-client-secrets
                  items:
                    - key: UPV_client_cert.pem
                      path: rabbitmq-certificates/UPV_client_cert.pem
                    - key: UPV_client_csr.pem
                      path: rabbitmq-certificates/UPV_client_csr.pem
                    - key: UPV_client_key.pem
                      path: rabbitmq-certificates/UPV_client_key.pem
                    - key: rootCA_cert.pem
                      path: rabbitmq-certificates/rootCA_cert.pem
              - configMap:
                  name: fem-client-launcher
                  items:
                    - key: launcher.json
                      path: launcher.json
              - configMap:
                  name: fem-client-config
                  items:
                    - key: config.py
                      path: config.py
            defaultMode: 420
      initContainers:
        - name: set-volume-permissions
          image: busybox:1.33
          command: ['sh', '-c', 'chown -R 1000:1000 /app/data && chown 1000:1000 /app/logs']
          volumeMounts:
            - mountPath: /app/logs
              name: fem-client-vol
              subPath: logs/
            - mountPath: /app/data
              name: fem-client-vol
              subPath: data/
      containers:
        - name: fem-client
          image: registry.gitlab.bsc.es/fl/fem-client:v2.3-test
          command:
            - python
            - receiver.py
          workingDir: /app
          resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '2'
              memory: 8Gi
          volumeMounts:
            - name: config-env
              mountPath: /app/.env
              subPath: .env
            - name: fem-client-vol
              mountPath: /app/logs
              subPath: logs/
            - name: fem-client-vol
              mountPath: /app/data
              subPath: data/
            - name: homes
              mountPath: /app/sandbox
            - name: config
              mountPath: /app/config
          imagePullPolicy: Always
      restartPolicy: Always
      nodeSelector:
        chaimeleon.eu/target: core-services
      priorityClassName: core-applications
