kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fem-client-pvc
  namespace: eucaim-fed-computation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs