apiVersion: v1
data:
  UPV_client_cert.pem: >-
    <cert content base64>
  UPV_client_csr.pem: >-
    <cert content base64>
  UPV_client_key.pem: >-
    <cert content base64>
  rootCA_cert.pem: >-
    <cert content base64>
kind: Secret
metadata:
  name: fem-client-secrets
  namespace: eucaim-fed-computation
type: Opaque
