kind: Service
apiVersion: v1
metadata:
  name: fem-client
  namespace: eucaim-fed-computation
spec:
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: webservice
