apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-full-config
  namespace: orthanc-full
data:
  ORTHANC_JSON: |
    {
      "Name": "Orthanc Production",
      "RemoteAccessAllowed": true,
      "AuthenticationEnabled": false,
      "BehindReverseProxy": true,
      "HttpRoot": "/orthanc-full/",
      "DicomWeb": {
        "Enable": true,
        "Root": "/dicom-web/"
      },
      "Plugins": [
        "/usr/share/orthanc/plugins/",
        "/usr/share/orthanc/plugins-available/libStorageLink_ChangeCallback.so"
      ],
      "StorageLink": {
        "LinkDirectory": "/var/lib/orthanc/storage_link/"
      },
      "StableAge": 5,
      "UserMetadata": { 
        "patientID-encrypted": 1024  
      },
      "LuaScripts": [
      "/var/lib/orthanc/scripts/script.lua"
      ],
      "OrthancExplorer2": {
        "Theme": "dark",
        "UiOptions": {
          "EnableShares": false,
          "EnableOpenInOhifViewer3": true,
          "OhifViewer3PublicRoot": "https://breastscan.imaging.i3m.upv.es/ohif-full/",
          "EnableUpload": true,
          "EnableDeleteResources": true,
          "EnableDownloadZip": false,
          "EnableDownloadDicomDir": false,
          "EnableDownloadDicomFile": false,
          "EnableAnonymization": false,
          "EnableModification": false,
          "EnableSendTo": false,
          "EnableSettings": true,
          "EnableLinkToLegacyUi": false,
          "EnableEditLabels": false,
          "EnableAddSeries": true,
          "EnableApiViewMenu": true,
          "CustomButtons": {
            "bulk-studies": [
              {
                "Label": "Test",
                "Tooltip": "Go to Wrapper",
                "Icon": "bi bi-box-arrow-in-right",
                "HttpMethod": "GET",
                "Target": "_blank",
                "Url": "http://orthanc-eucaim.grycap.i3m.upv.es/wrapper/?uuids={CommaSeparatedUUIDs}&dicoms={CommaSeparatedDicomIds}"
              }
            ]
          }
        },
        "Keycloak": {
          "Enable": true,
          "Url": "https://breastscan.imaging.i3m.upv.es/auth/",
          "Realm": "EUCAIM-NODE",
          "ClientId": "orthanc"
        }
      },
      "Authorization": {
        "WebServiceRootUrl": "http://orthanc-full-auth-service:8000/",
        "WebServiceUsername": "${SVC_INTERNAL_USER}",
        "WebServicePassword": "${SVC_INTERNAL_PASSWORD}",
        "StandardConfigurations": [
          "osimis-web-viewer",
          "stone-webviewer",
          "orthanc-explorer-2",
          "ohif",
          "stl"
        ],
        "TokenHttpHeaders": ["api-key"],
        "CheckedLevel": "studies"
      }
    }
  permissions.json: |
    {
      "roles": {
        "admin-role": {
          "authorized-labels": ["*"],
          "permissions": [
            "anonymize",
            "audit-logs",
            "delete",
            "download",
            "modify",
            "send",
            "share",
            "view",
            "worklists",
            "admin-permissions",
            "edit-labels",
            "q-r-remote-modalities",
            "settings",
            "upload"
          ]
        },
        "doctor-role": {
          "authorized-labels": ["*"],
          "permissions": ["view", "download", "share", "send"]
        },
        "external-role": {
          "authorized-labels": ["external", "Label3", "Label5"],
          "permissions": ["view", "download"]
        }
      },
      "available-labels": []
    }