
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orthanc-full-storage-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/hostpath-provisioner/orthanc-full/orthanc-storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-full-storage
  namespace: orthanc-full
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
  volumeName: orthanc-full-storage-pv
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: orthanc-full-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/hostpath-provisioner/orthanc-full/orthanc-db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-full-db-pvc
  namespace: orthanc-full
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
  volumeName: orthanc-full-db-pv

