
parent=keycloak
import=common/chaimeleon

styles=css/login.css css/tile.css css/style.css
scripts=node_modules/jquery/dist/jquery.min.js js/script.js
# js/jquery-3.6.0.min.js

#kcRoleCard=pf-l-split
#kcRoleCardImage=pf-l-split__item
#kcRoleCardText=pf-l-split__item pf-m-fill

kcRoleCard=inline-block margin-top
kcRoleCardImage=role-card-image
kcRoleCardText=role-card-text
kcRoleCardCheck=pf-c-check__input
kcRoleCardCheckLabel=pf-c-check__label
kcRolesFullList=authorised_technical_data_manager clinical_staff dataset_administrator data_scientist external_researcher application_developer data_protection_officer cloud_services_and_security_manager

