apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaimeleon-users-role-namespace
rules:
- apiGroups: ["*"]
  resources: ["secrets","pods","pods/log","pods/exec", "jobs", "deployments", "replicasets", "daemonsets", "replicationcontrollers", "statefulsets","cronjobs", "configmaps", "container", "persistentvolumeclaims", "horizontalpodautoscalers", "services", "datasets-consumer"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["*"]
  resources: ["events", "ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["ingresses"]
  verbs: ["create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaimeleon-users-role-cluster
rules:
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get","watch"]
- apiGroups: ["*"]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
