apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/hostpath-provisioner/dataset-service/postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  storageClassName: ""
  volumeName: pv-postgres-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dataset-service-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/hostpath-provisioner/dataset-service/dataset-service-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-service-data
spec:
  storageClassName: ""
  volumeName: pv-dataset-service-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datalake-data
spec:
  storageClassName: ""
  volumeName: pv-datalake
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-datalake
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/hostpath-provisioner/dataset-service/datalake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-data
spec:
  storageClassName: ""
  volumeName: pv-datasets
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-datasets
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/hostpath-provisioner/dataset-service/datasets
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orthanc-storage-ds
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/hostpath-provisioner/orthanc/orthanc-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-storage
  namespace: dataset-service
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-orthanc-storage-ds
