# Ref: https://github.com/chaimeleon-eu/helm-chart-guacamole/blob/master/values.yaml

guacamole:
  image:
#   repository: guacamole/guacamole
    repository: harbor.chaimeleon-eu.i3m.upv.es/dockerhub/guacamole/guacamole

guacd:
  image:
#   repository: guacamole/guacd
    repository: harbor.chaimeleon-eu.i3m.upv.es/dockerhub/guacamole/guacd

dbcreation:
  image:
#   repository: bitnami/postgresql
    repository: harbor.chaimeleon-eu.i3m.upv.es/dockerhub/bitnami/postgresql
    tag: "11.12.0-debian-10-r5"  # 11.9.0-debian-10-r73

serviceAccount:
  # Specifies whether a service account should be created
  create: false

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: "true"
     nginx.ingress.kubernetes.io/proxy-body-size: 100000m
#    nginx.ingress.kubernetes.io/rewrite-target: /guacamole/$1
  hosts:
    - host: chaimeleon-eu.i3m.upv.es
      paths:
        - '/guacamole/?(.*)'

priorityClassName: "core-applications"

resources: 
  requests:
    memory: '512Mi'
    cpu: '200m'
  limits:
    memory: '2Gi'
    cpu: 1
    
postgres:
  hostname: "postgresql"
  port: "5432"
  database: "guacamole"
  user: "XXXXXXXX"
  password: "XXXXXXXXXXX"

OIDC:
  authorization_endpoint: "https://chaimeleon-eu.i3m.upv.es/auth/realms/CHAIMELEON/protocol/openid-connect/auth/"
  jwks_endpoint: "https://chaimeleon-eu.i3m.upv.es/auth/realms/CHAIMELEON/protocol/openid-connect/certs/"
  issuer: "https://chaimeleon-eu.i3m.upv.es/auth/realms/CHAIMELEON"
  clientID: "guacamole"
  redirect_uri: "https://chaimeleon-eu.i3m.upv.es/guacamole/"
  username_claim_type: "username"
  groups_claim_type: "groups"

