image:
  registry: harbor.eucaim-node.i3m.upv.es
  repository: dockerhub/bitnamilegacy/postgresql
  tag: 17.2.0-debian-12-r5
auth:
  postgresPassword: XXXXXXXXXXXX
  username: guacamole
  password: password
  database: guacamole
  adminPassword: xxxxxxxxx
primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 500Mi
      cpu: 500m
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-applications
  persistence:
    enabled: true
    existingClaim: guacamole-postgresql
volumePermissions:
  enabled: true
  image:
    registry: harbor.eucaim-node.i3m.upv.es
    repository: core-services/bitnami/os-shell
    digest: sha256:6311d07df0957a0bdb467838c93ba1f4f6c58a741c02f9ede618f17d60982828
