apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-deployment
  labels:
    app: focus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focus
  template:
    metadata:
      labels:
        app: focus
    spec:
      containers:
      - name: focus
        image: docker.verbis.dkfz.de/eucaim/focus:eucaim
        imagePullPolicy: Always
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: FOCUS_API_KEY
        - name: BEAM_PROXY_URL
          value: http://beam-proxy-service:8081
        - name: BEAM_APP_ID_LONG
          value: focus.YOUR_PROVIDER.broker.eucaim.cancerimage.eu
        - name: RETRY_COUNT
          value: "10"
        - name: ENDPOINT_URL
          value: http://dataset-service-backend-service.dataset-service.svc.cluster.local:11000/api/datasets/eucaimSearch
        - name: AUTH_HEADER
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: DATASET_SERVICE_AUTH_HEADER
        - name: ENDPOINT_TYPE
          value: omop
        - name: PROVIDER
          value: YOUR_PROVIDER
        - name: PROVIDER_ICON
          value: ""
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 256Mi
