apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobman-service-logs
  namespace: jobman-service
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256M