apiVersion: v1
kind: Service
metadata:
  name: jobman-service
  namespace: jobman-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: api
  selector:
    app: jobman-service-deployment
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobman-service-deployment
  namespace: jobman-service
spec:
  selector:
    matchLabels:
      app: jobman-service-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobman-service-deployment
    spec:
      priorityClassName: core-services
      nodeSelector:
        chaimeleon.eu/target: core-services
      serviceAccountName: jobman-serviceaccount
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: harbor.eucaim-node.i3m.upv.es/core-services/jobman-service:2.3.1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
        imagePullPolicy: Always
        name: jobman-service-deployment-container
        env:
        - name: SETTINGS_FILE
          value: /opt/jobman/settings.json
        resources:
          requests:
            memory: "4Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
          name: api
        volumeMounts:
          - name: logs
            mountPath: /var/log/jobman
          - name: webservice-configmap
            mountPath: /opt/jobman/settings.json
            subPath: settings.json
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: jobman-service-logs
        - name: webservice-configmap
          configMap:
            defaultMode: 420
            name: webservice-config

