apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      priorityClassName: core-services
      volumes:
        - name: vol-themes-data
          persistentVolumeClaim:
            claimName: themes-data
        - name: vol-standalone-deployments
          persistentVolumeClaim:
            claimName: standalone-deployments
        - name: keycloak-conf
          configMap:
            name: keycloak-conf
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:13.0.1
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1500m"
          limits:
            memory: "1000Mi"
            cpu: "1500m"
        volumeMounts:
          - mountPath: "/opt/jboss/keycloak/themes"
            name: vol-themes-data
          - mountPath: "/opt/jboss/keycloak/standalone/deployments/"
            name: vol-standalone-deployments
            readOnly: false
          - name: keycloak-conf
            mountPath: "/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml"
            subPath: standalone-ha.xml
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "XXXXXXXXXX"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: db:5432
        - name: DB_USER
          value: "keycloak-user"
        - name: DB_PASSWORD
          value: "XXXXXXXXXX"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
