apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      priorityClassName: core-services
      nodeSelector: 
        chaimeleon.eu/target: core-services
      volumes:
        - name: vol-themes-data
          persistentVolumeClaim:
            claimName: themes-data
        - name: vol-standalone-deployments
          persistentVolumeClaim:
            claimName: standalone-deployments
      containers:
      - name: keycloak
        image: "quay.io/keycloak/keycloak:26.2.0"
        args: ["start", "--http-relative-path=/auth", "--features=token-exchange", "--http-enabled=true", "--proxy-headers=xforwarded"]
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1500m"
#         limits:
#           memory: "1000Mi"
#           cpu: "1500m"
        volumeMounts:
          - name: vol-themes-data
            mountPath: "/opt/keycloak/themes/eucaim-node/"
            subPath: "eucaim-node"
          - name: vol-standalone-deployments
            mountPath: "/opt/keycloak/providers/keycloak-event-listener-email-to-admin-1.0.6.jar"
            subPath: "keycloak-event-listener-email-to-admin-1.0.6.jar"
            readOnly: false
          - name: vol-standalone-deployments
            mountPath: "/opt/keycloak/providers/keycloak-required-action-user-validated-1.0.5.jar"
            subPath: "keycloak-required-action-user-validated-1.0.5.jar"
            readOnly: false
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "XXXXXXXXXX"

        # Doc: https://www.keycloak.org/server/all-config
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: db
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          value: "keycloak-user"
        - name: KC_DB_PASSWORD
          value: "XXXXXXXXXX"
        - name: KC_HOSTNAME
          # This is recommended for checking the "host" header of requests
          value: "eucaim-node.i3m.upv.es"

        # Doc: https://www.keycloak.org/server/configuration-provider
        - name: KC_SPI_EVENTS_LISTENER_EMAIL_TO_ADMIN_EMAIL_RECEIVERS
          value: "admin@example.com"
        - name: KC_SPI_EVENTS_LISTENER_EMAIL_TO_ADMIN_EMAIL_SUBJECT
          value: "EUCAIM-Node - User account created or updated"
          
        - name: KC_SPI_REQUIRED_ACTION_USER_VALIDATED_ROLE_FOR_VALIDATED
          value: "validated_user"
        - name: KC_SPI_REQUIRED_ACTION_USER_VALIDATED_ROLE_FOR_REJECTED
          value: "rejected_user"
        - name: KC_SPI_REQUIRED_ACTION_USER_VALIDATED_MESSAGE_FOR_PENDING
          value: "Your account is pending to be validated and assigned to a project to be able to access to the services. You will be notified when that occurs."
        - name: KC_SPI_REQUIRED_ACTION_USER_VALIDATED_MESSAGE_FOR_REJECTED
          value: "Your account request has not been accepted."
          
        - name: KC_SPI_EVENTS_LISTENER_EMAIL_INCLUDE_EVENTS
          # This is to notify the user by email when the account is disabled due to brute force attack detection
          value: "user_disabled_by_permanent_lockout,user_disabled_by_temporary_lockout"

        ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/realms/master
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
