# This is the template of the k8s job launched whenever a subproject is created or updated.
# Template variables that will be replaced by the launcher (the Dataset-service):
#   __PROJECT_CODE__, __SUBPROJECT_CODE__, __SUBPROJECT_NAME__, __SUBPROJECT_DESCRIPTION__, __SUBPROJECT_EXTERNAL_ID__
# NOTE: the script for create (create-project.sh) should be idempotent, the result should be the same if called multiple times.

apiVersion: batch/v1
kind: Job
metadata:
  # name: it is set by the caller
  # namespace: it is set by the caller
spec:
  template:
    spec:
      volumes:
        - name: dataset-service-data-volume
          persistentVolumeClaim:
            claimName: dataset-service-data
      containers:
        - name: subproject-management
          image: harbor.eucaim-node.i3m.upv.es/core-services/dataset-service-on-event-jobs:1.0
          #imagePullPolicy: Always
          workingDir: "/home/ubuntu/scripts"
          command: ["/bin/bash"]
          args: ["/home/ubuntu/scripts/create-subproject.sh"]
          volumeMounts:
            - mountPath: "/home/ubuntu/scripts"
              subPath: "on-event-jobs/scripts"
              name: dataset-service-data-volume
          env:
            - name: PROJECT_CODE
              value: "__PROJECT_CODE__"
            - name: SUBPROJECT_CODE
              value: "__SUBPROJECT_CODE__"
            - name: SUBPROJECT_NAME
              value: "__SUBPROJECT_NAME__"
            - name: SUBPROJECT_DESCRIPTION
              value: "__SUBPROJECT_DESCRIPTION__"
            - name: SUBPROJECT_EXTERNAL_ID
              value: "__SUBPROJECT_EXTERNAL_ID__"
                
            - name: KEYCLOAK_TOKEN_ENDPOINT
              value: "https://eucaim-node.i3m.upv.es/auth/realms/EUCAIM-NODE/protocol/openid-connect/token"

            - name: QPI_ADMIN_ENDPOINT
              #value: "http://gateway.quibim.svc.cluster.local/care/admin/"
              value: "https://qpinsights.eucaim-node.i3m.upv.es/care/admin/"
            - name: QPI_ADMIN_CLIENT_ID
              value: "qpinsights"
            - name: QPI_ADMIN_USERNAME
              # This user should be created specially for that purpose in the auth service and QP-Insights, see the user-management-job-template for more details.
              value: "qpi-user-creator"
            - name: QPI_ADMIN_PASSWORD
              value: "XXXXXXXXXXXXXXXX"
            
            - name: DS_ENDPOINT
              #value: "http://dataset-service-backend.dataset-service.svc.cluster.local/api/"
              value: "https://eucaim-node.i3m.upv.es/dataset-service/api/"
            - name: DS_CLIENT_ID
              value: "dataset-explorer"
			  # Here the same QPI_ADMIN_USERNAME and QPI_ADMIN_PASSWORD previously defined is used to access also to the dataset-service
			  # In this case (for subprojects management) you must assign also to this user the role dataset-service:admin_projects.
            
      restartPolicy: Never  # no restart container if fails
      nodeSelector: 
        chaimeleon.eu/target: core-services
  backoffLimit: 0   # no retry to launch pod if fails
  ttlSecondsAfterFinished: 86400   # auto remove the job 24 hours after finish
