# This is the template of the k8s job launched whenever a user is created, updated or deleted.
# Template variables that will be replaced by the launcher (the Dataset-service):
#   __OPERATION__, __TENANT_USERNAME__, __TENANT_ROLES__, __TENANT_SITE__, __TENANT_PROJECTS__
# __OPERATION__ will be "create" or "delete".
# __TENANT_ROLES__ will be a list of roles separated by ":". Example: "dataset-administrator:data-scientists"
# __TENANT_PROJECTS__ will be a list of projects separated by ":". Example: "CHAIMELEON:PRIMAGE"
# __TENANT_SITE__ can be empty if the user has no site assigned (usually the site is mandatory only for some roles, those who upload data).
# NOTE: the script for create (create-user.sh) should be idempotent, the result should be the same if called multiple times.

apiVersion: batch/v1
kind: Job
metadata:
  # name: it is set by the caller
  # namespace: it is set by the caller
spec:
  template:
    spec:
      volumes:
        - name: dataset-service-data-volume
          persistentVolumeClaim:
            claimName: dataset-service-data
        - name: homes-volume
          hostPath:
            path: /var/hostpath-provisioner/data/homes/users
            type: Directory
      containers:
        - name: user-management
          image: harbor.eucaim-node.i3m.upv.es/core-services/dataset-service-on-event-jobs:1.0-1
          #imagePullPolicy: Always
          workingDir: "/home/ubuntu/scripts"
          command: ["/bin/bash"]
          args: ["/home/ubuntu/scripts/__OPERATION__-user.sh"]
          volumeMounts:
            - mountPath: "/home/ubuntu/scripts"
              subPath: "on-event-jobs/scripts"
              name: dataset-service-data-volume
            - name: homes-volume
              mountPath: /mnt/homes
          env:
            - name: TENANT_NAME
              value: "__TENANT_USERNAME__"
            - name: TENANT_ROLES
              value: "__TENANT_ROLES__"
            - name: TENANT_SITE
              value: "__TENANT_SITE__"
            - name: TENANT_PROJECTS
              value: "__TENANT_PROJECTS__"

            - name: K8S_ENDPOINT
              value: "__K8S_ENDPOINT__"
            - name: K8S_TOKEN
              value: "__K8S_TOKEN__"
              
            - name: MOUNTED_DIR_PERSISTENT_HOMES
              value: "/mnt/homes"
              
            - name: KEYCLOAK_TOKEN_ENDPOINT
              value: "__KEYCLOAK_TOKEN_ENDPOINT__"

            - name: KEYCLOAK_ADMIN_ENDPOINT
              value: "__KEYCLOAK_ADMIN_ENDPOINT__"
            - name: KEYCLOAK_CLIENT
              # You must create that client as a service account in Keycloak.
              # In order to add API tokens as custom attributes in the users:
              #  - Ensure that the "Unmanaged Attributes" are enabled in the "Realm settings" -> tab "General".
              #  - The following roles must be added to the service account roles 
              #    (and also in the "dedicated scope" of the client if "full scope" is not enabled): 
              #     "realm-management/query-users", "realm-management/view-users", "realm-management/manage-users".
              value: "dataset-service"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "__KEYCLOAK_CLIENT_SECRET__"

            - name: GUACAMOLE_ENDPOINT
              value: "http://guacamole-guacamole.guacamole.svc.cluster.local/guacamole/"
            - name: GUACAMOLE_ADMIN_USER
              # You must create that user in Guacamole
              value: "eucaim-user-creator"
            - name: GUACAMOLE_ADMIN_PASSWORD
              value: "__GUACAMOLE_ADMIN_PASSWORD__"
              
            - name: EXTERNAL_SHARING_SERVICE_ENDPOINT
              value: "http://external-sharing-service.external-sharing-service.svc.cluster.local:80"
              
              # Following params are domains to be included in the network policy as allowed destinations from pods in the user namespace
            - name: MAIN_DOMAIN_NAME
              value: "__MAIN_DOMAIN_NAME__"
            - name: HARBOR_DOMAIN_NAME
              value: "harbor.eucaim-node.i3m.upv.es"
            
      restartPolicy: Never  # no restart container if fails
      nodeSelector: 
        chaimeleon.eu/target: core-services
  backoffLimit: 0   # no retry to launch pod if fails
  ttlSecondsAfterFinished: 86400   # auto remove the job 24 hours after finish
