# This is the template of the k8s job launched whenever a user is created, updated or deleted.
# Template variables that will be replaced by the launcher (the Dataset-service):
#   __OPERATION__, __TENANT_USERNAME__, __TENANT_ROLES__, __TENANT_SITE__, __TENANT_PROJECTS__
# __OPERATION__ will be "create" or "delete".
# __TENANT_ROLES__ will be a list of roles separated by ":". Example: "dataset-administrator:data-scientists"
# __TENANT_PROJECTS__ will be a list of projects separated by ":". Example: "CHAIMELEON:PRIMAGE"
# __TENANT_SITE__ can be empty if the user has no site assigned (usually the site is mandatory only for some roles, those who upload data).
# NOTE: the script for create (create-user.sh) should be idempotent, the result should be the same if called multiple times.

apiVersion: batch/v1
kind: Job
metadata:
  # name: it is set by the caller
  # namespace: it is set by the caller
spec:
  template:
    spec:
      serviceAccountName: user-management-sa
      volumes:
        - name: dataset-service-data-volume
          persistentVolumeClaim:
            claimName: dataset-service-data
        - name: homes-volume
          hostPath:
            path: /var/hostpath-provisioner/data/homes/users
            type: Directory
      containers:
        - name: user-management
          image: harbor.eucaim-node.i3m.upv.es/core-services/dataset-service-on-event-jobs:1.0
          #imagePullPolicy: Always
          workingDir: "/home/ubuntu/scripts"
          command: ["/bin/bash"]
          args: ["/home/ubuntu/scripts/__OPERATION__-user.sh"]
          volumeMounts:
            - mountPath: "/home/ubuntu/scripts"
              subPath: "on-event-jobs/scripts"
              name: dataset-service-data-volume
            - name: homes-volume
              mountPath: /mnt/homes
          env:
            - name: TENANT_NAME
              value: "__TENANT_USERNAME__"
            - name: TENANT_ROLES
              value: "__TENANT_ROLES__"
            - name: TENANT_SITE
              value: "__TENANT_SITE__"
            - name: TENANT_PROJECTS
              value: "__TENANT_PROJECTS__"

            # - name: K8S_ENDPOINT
            #   value: "https://mininode.imaging.i3m.upv.es:6443"
            # - name: K8S_TOKEN
            #   value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkxvM19kZlFNNzRwbGhCRWJmVWR2ck15S3Vtb19CR0V1MEpGRmxhaUhXWkUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkYXRhc2V0LXNlcnZpY2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoidXNlci1tYW5hZ2VtZW50LXNhLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InVzZXItbWFuYWdlbWVudC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImRiYTRiODM5LWU4MzUtNGQ1MC04ZmM2LTEzOTFhZDRkYjgzMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkYXRhc2V0LXNlcnZpY2U6dXNlci1tYW5hZ2VtZW50LXNhIn0.UcoZr4H6WwwFYFG874Mwu7ixM-rN4et9FxsOuKhMkQ45kiSPjMTYGYAoo0cWLC1mj4WmiDB2YIosPKvvnnLlOpq4YFxhl3sHb2S_eOxXxnl2gfHvE8nE60GYRSBYFKKjxvhVFJlP05ATu30CybAOXtDDKavPTVCrS-Kt9x2SphC4EW_uoEn3HCdPthKPf000rc7wrCum7Eif2tYr-bTtXN0wNtZblheB7vzt7t9PQsa19IYOfEgGOWYHXdotM2rJ01O4TR-EZqERYoh8vlUdpLcVFpa9Mp4f7d-6dNQgzJ-kX_mw-N07qDaNNwH0BVfpMBzmqa1_xl_VYTT-onWkwg"
              
            - name: MOUNTED_DIR_PERSISTENT_HOMES
              value: "/mnt/homes"
              
            - name: KEYCLOAK_TOKEN_ENDPOINT
              value: "https://mininode.imaging.i3m.upv.es/auth/realms/EUCAIM-NODE/protocol/openid-connect/token"

            - name: KEYCLOAK_ADMIN_ENDPOINT
              value: "https://mininode.imaging.i3m.upv.es/auth/admin/realms/EUCAIM-NODE/"
            - name: KEYCLOAK_CLIENT
              # You must create that client as a service account in Keycloak.
              # In order to add API tokens as custom attributes in the users:
              #  - Ensure that the "Unmanaged Attributes" are enabled in the "Realm settings" -> tab "General".
              #  - The following roles must be added to the service account roles 
              #    (and also in the "dedicated scope" of the client if "full scope" is not enabled): 
              #     "realm-management/query-users", "realm-management/view-users", "realm-management/manage-users".
              value: "dataset-service"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "Wgq4kpBLa0Stjx6FtHoMoT1yBNd02ErT"

            - name: GUACAMOLE_ENDPOINT
              value: "http://guacamole-guacamole.guacamole.svc.cluster.local/guacamole/"
            - name: GUACAMOLE_ADMIN_USER
              # You must create that user in Guacamole
              value: "eucaim-user-creator"
            - name: GUACAMOLE_ADMIN_PASSWORD
              value: "hCbsows1wS89rnCI5QIDGFT9"
              
            - name: EXTERNAL_SHARING_SERVICE_ENDPOINT
              value: "http://external-sharing-service.external-sharing-service.svc.cluster.local:80"
              
              # Following params are domains to be included in the network policy as allowed destinations from pods in the user namespace
            - name: MAIN_DOMAIN_NAME
              value: "mininode.imaging.i3m.upv.es"
            - name: HARBOR_DOMAIN_NAME
              value: "harbor.eucaim-node.i3m.upv.es"
            
      restartPolicy: Never  # no restart container if fails
      nodeSelector: 
        chaimeleon.eu/target: core-services
  backoffLimit: 0   # no retry to launch pod if fails
  ttlSecondsAfterFinished: 86400   # auto remove the job 24 hours after finish
