apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-gateway
  template:
    metadata:
      labels:
        app: internal-gateway
    spec:
      volumes:
      - name: config
        configMap:
          name: internal-gateway-config
      - name: certs
        secret:
          secretName: harbor.eucaim-node.i3m.upv.es
      containers: 
      - image: "harbor.eucaim-node.i3m.upv.es/dockerhub/library/nginx:1.19-alpine"
        name: internal-gateway
        env:
        command: 
        - '/bin/sh'
        - '-c'
        - "exec nginx -g 'daemon off;'"
        ports:
          - containerPort: 443
            name: gatewayport
        volumeMounts:
          - mountPath: "/etc/nginx/nginx.conf"
            name: config
            subPath: nginx-config
          - mountPath: "/etc/nginx/certs"
            name: certs
        # Liveness probe is important to regenerate pod when the certificate expires to reload from the secret
        # httpget method does not check the certificate, so we use exec command method with curl
        livenessProbe:
          exec:
            command: ['curl', 'https://harbor.eucaim-node.i3m.upv.es:5000/healthz']
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
      priorityClassName: core-services
      restartPolicy: Always
      nodeSelector:
        chaimeleon.eu/target: core-services

---
apiVersion: v1
kind: Service
metadata:
  name: internal-gateway
spec:
  selector:
    app: internal-gateway
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 5000
    port: 443
    targetPort: gatewayport
