apiVersion: v1
kind: Secret
metadata:
  name: quibim-secrets
type: Opaque
data:
  {{- range $key, $secret := $.Values.quibimSecrets }}
  {{ $key }}: {{ $secret | b64enc | quote }}
  {{- end }}
  
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.username | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.password | b64enc | quote }}
  MONGO_URL: {{ include "quibim-precision.MongoURL" . | b64enc | quote }}
  
  BACK_CLIENT_SECRET: {{ .Values.back.oidcClientSecret | b64enc | quote }}
  
  QPLINK_CLIENT_SECRET: {{ .Values.qplink.oidcClientSecret | b64enc | quote }}

