apiVersion: v1
kind: ServiceAccount
metadata:
  name: qpi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qpi-launch-analysis-jobs
rules:
  # create jobs is required to launch analysis
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qpi-launch-analysis-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qpi-launch-analysis-jobs
subjects:
  - kind: ServiceAccount
    name: qpi
    namespace: {{ .Release.Namespace }}
