
namespace: kyverno

createSelfSignedCert: false

config:
  resourceFilters: '[Event,*,*][*,kube-system,*][*,kube-public,*][*,kube-node-lease,*][Node,*,*][APIService,*,*][TokenReview,*,*][SubjectAccessReview,*,*][SelfSubjectAccessReview,*,*][*,kyverno,*][Binding,*,*][ReportChangeRequest,*,*][ClusterReportChangeRequest,*,*]'

#[ReplicaSet,*,*]

rbac:
  create: true
  serviceAccount:
    create: true
    name: kyverno

image:
  repository: ghcr.io/kyverno/kyverno
  tag: v1.4.3

initImage:
  repository: ghcr.io/kyverno/kyvernopre
  tag: v1.4.3

serviceMonitor:
  enabled: false

# https://kyverno.io/policies/pod-security/
podSecurityStandard: baseline
podSecuritySeverity: high
validationFailureAction: enforce