
ingress:
  enabled: true
  hostname: "chaimeleon-eu.i3m.upv.es"
  path: "/apps/?(.*)"
# tls: true
# extraHosts:
# - name: "chaimeleon-eu.i3m.upv.es"
#   path: "/apps/?(.*)"
  extraTls:
  - hosts:
    - "chaimeleon-eu.i3m.upv.es"
#   secretName: "chaimeleon-eu.i3m.upv.es"
# secrets:
# - name: "chaimeleon-eu.i3m.upv.es"
  annotations:
    # Lo siguiente es necesario cuando el proxy devuelve "502 - bad gateway" 
    # y en log del proxy aparece: ERROR upstream sent too big header while reading response header from upstream
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k

postgresql:
  enabled: true
  postgresqlPassword: XXXXXXXXXXXXX
  replication:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
    storageClass: cephfs
  primary:
    priorityClassName: "core-applications"
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m

## https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
authProxy:
  enabled: true
  external: false
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m
  oauthLoginURI: "/apps/oauth2/start?rd=%2Fapps%2F"
  oauthLogoutURI: "/apps/oauth2/sign_out?rd=%2Fapps%2F"
# oauthLoginURI: "/apps/oauth2/login"
# oauthLogoutURI: "/apps/oauth2/logout"
  skipKubeappsLoginPage: false
  provider: oidc
  clientID: "kubernetes"
  clientSecret: XXXXXXXXXXXXX
  ## python -c 'import os,base64; print base64.urlsafe_b64encode(os.urandom(16))'
  cookieSecret: XXXXXXXXXXXXX
  additionalFlags:
    - "--oidc-issuer-url=https://chaimeleon-eu.i3m.upv.es/auth/realms/CHAIMELEON"
    - "--proxy-prefix=/apps/oauth2"
    - "--scope=openid email"
    - "--set-authorization-header=true"


frontend:
  replicaCount: 1
  priorityClassName: "core-applications"
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m

dashboard:
  replicaCount: 1
  priorityClassName: "core-applications"
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m  

kubeops:
  priorityClassName: "core-applications"
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m

assetsvc:
  replicaCount: 1
  priorityClassName: "core-applications"
  resource: "avoid-chart-error-in-IF"
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m

apprepository:
  priorityClassName: "core-applications"
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m  
  initialRepos:
    - name: chaimeleon-library
      url: "https://chaimeleon-eu.i3m.upv.es:10443/chartrepo/chaimeleon-library"


