# https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaimeleon-oidc-admins-cluster-binding-cluster-admin
subjects:
- kind: Group
  name: "oidc:admins"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaimeleon-oidc-data-scientist-binding-view
  namespace: "chaimeleon"
subjects:
- kind: Group
  name: "oidc:data-scientist"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaimeleon-oidc-data-scientist-binding-edit
  namespace: "chaimeleon"
subjects:
- kind: Group
  name: "oidc:data-scientist"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaimeleon-oidc-application-developer-binding-view
  namespace: "chaimeleon"
subjects:
- kind: Group
  name: "oidc:application-developer"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaimeleon-oidc-application-developer-binding-edit
  namespace: "chaimeleon"
subjects:
- kind: Group
  name: "oidc:application-developer"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaimeleon-oidc-palollo-cluster-binding-cluster-admin
subjects:
- kind: User
  name: "oidc:palollo"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tracer-service-oidc-asalic-binding-view
  namespace: "tracer-service"
subjects:
- kind: User
  name: "oidc:asalic"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tracer-service-oidc-asalic-binding-edit
  namespace: "tracer-service"
subjects:
- kind: User
  name: "oidc:asalic"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit


