# Doc: https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#parameters

postgresql:
  enabled: true
  image:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  auth:
    username: "postgres"
    password: "XXXXXXXXXXXXX"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: cephfs
    priorityClassName: "core-applications"
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 200Mi
      cpu: 200m

ingress:
  enabled: true
  hostname: "eucaim-node.i3m.upv.es"
  path: "/apps/?(.*)"
# tls: true
# extraTls:
# - hosts:
#   - "eucaim-node.i3m.upv.es"
#   secretName: "eucaim-node.i3m.upv.es"
# secrets:
# - name: "eucaim-node.i3m.upv.es"
  ingressClassName: "nginx"
  annotations:
    # The following line is needed when the proxy returns "502 - bad gateway" 
    # and in the proxy log apears: ERROR upstream sent too big header while reading response header from upstream
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k

## https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
authProxy:
  enabled: true
  external: false
  image:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  oauthLoginURI: "/apps/oauth2/start?rd=%2Fapps%2F"
  oauthLogoutURI: "/apps/oauth2/sign_out?rd=https%3A%2F%2Feucaim-node.i3m.upv.es%2Fauth%2Frealms%2FEUCAIM-NODE%2Fprotocol%2Fopenid-connect%2Flogout%3Fclient_id%3Dkubernetes%26post_logout_redirect_uri%3Dhttps%3A%2F%2Feucaim-node.i3m.upv.es%2Fapps%2F"
# oauthLoginURI: "/apps/oauth2/login"
# oauthLogoutURI: "/apps/oauth2/logout"
  skipKubeappsLoginPage: true
  provider: oidc
  clientID: "kubernetes"
  clientSecret: XXXXXXXXXXXXX
  ## Generate a cookie secret with: python3 -c 'import os,base64; print(base64.urlsafe_b64encode(os.urandom(16)))'
  cookieSecret: XXXXXXXXXXXXX
  extraFlags:
    - "--oidc-issuer-url=https://eucaim-node.i3m.upv.es/auth/realms/EUCAIM-NODE"
    - "--proxy-prefix=/apps/oauth2"
    - "--scope=openid email"
    - "--set-authorization-header=true"
    - "--cookie-name=oauth2kubeapps"
    - "--cookie-path=/apps/"
    - "--skip-provider-button=true"
    - "--whitelist-domain=eucaim-node.i3m.upv.es"
    - "--cookie-csrf-per-request=true"
    - "--skip-auth-regex=^\\/apps\\/config\\.json$"
    - "--skip-auth-regex=^\\/apps\\/site\\.webmanifest$"
    - "--skip-auth-regex=^\\/apps\\/custom_style\\.css$"
    - "--skip-auth-regex=^\\/apps\\/clr-ui\\.min\\.css$"
    - "--skip-auth-regex=^\\/apps\\/clr-ui-dark\\.min\\.css$"
    - "--skip-auth-regex=^\\/apps\\/custom_locale\\.json$"
    - "--skip-auth-regex=^\\/apps\\/favicon.*\\.png$"
    - "--skip-auth-regex=^\\/apps\\/favicon.*\\.ico$"
    - "--skip-auth-regex=^\\/apps\\/android-chrome-.*\\.png$"
    - "--skip-auth-regex=^\\/apps\\/static\\/"
    - "--skip-auth-regex=^\\/apps\\/apis\\/core\\/plugins\\/v1alpha1\\/configured-plugins$"
    - "--skip-auth-regex=^\\/apps\\/apis\\/kubeappsapis\\.core\\.plugins\\.v1alpha1\\.PluginsService\\/"
    - "--skip-auth-regex=^\\/apps\\/$"

frontend:
  image:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m
  priorityClassName: "core-applications"
  nodeSelector:
    chaimeleon.eu/target: core-services

dashboard:
  image:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m
  priorityClassName: "core-applications"
  nodeSelector:
    chaimeleon.eu/target: core-services

apprepository:
  image:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  syncImage:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m  
# initialRepos:
##  - name: bitnami
##    url: "https://charts.bitnami.com/bitnami"
##  - name: eucaim-node
##    url: "https://harbor.eucaim-node.i3m.upv.es/chartrepo/charts"
#   - name: eucaim-node
#     type: oci
#     url: "https://harbor.eucaim-node.i3m.upv.es/charts"
#     ociRepositories:
#       - desktop-tensorflow
  priorityClassName: "core-applications"
  nodeSelector:
    chaimeleon.eu/target: core-services

kubeappsapis:
  image:
    registry: "harbor.eucaim-node.i3m.upv.es/dockerhub"
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m
  priorityClassName: "core-applications"
  nodeSelector:
    chaimeleon.eu/target: core-services
