apiVersion: v1
kind: Namespace
metadata:
  name: jobman-service
annotations:
  description: This namespace contains all the resources needed to run the Jobman webservice

---
apiVersion: v1
kind: Namespace
metadata:
  name: jobman-service-exec
annotations:
  description: This namespace contains all the resources needed to run the jobs launched by Jobman, including the jobs themselves
---

apiVersion: v1
kind: ServiceAccount
metadata:
  # annotations:
  #   kubernetes.io/enforce-mountable-secrets: "true"
  name: jobman-serviceaccount
  namespace: jobman-service
annotations:
  description: Service account to launch jobman under, needed to assign roles that allows access to resources in another namespace (where the jobs are actually launched)
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-jobman-serviceaccount
  namespace: jobman-service-exec
annotations:
  description: Role from the namespace where the jobs are acttually launched, allowing Jobman to manage the jobs and their related resources
rules:
- apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
  resources: ["jobs", "pods", "configmaps", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
    - ""
  resources: ["events"]
  verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-jobman-serviceaccount
  namespace: jobman-service-exec
annotations:
  description: Bind the Jobman's service account from its namespace to the role in the namespace where the jobs are launched
subjects:
- kind: ServiceAccount
  name: jobman-serviceaccount
  namespace: jobman-service
roleRef:
 kind: Role
 name: role-jobman-serviceaccount
 apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-jobman-serviceaccount-configmap
  namespace: jobman-service
annotations:
  description: Allows Jobman's service account to access configmaps, needed to access the jobs' queue that is managed by a cron job not jobman itself
rules:
- apiGroups:
        - ""
  resources: ["configmaps"]
  verbs: ["get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-jobman-serviceaccount-configmap
  namespace: jobman-service
annotations:
  description: Bind Jobman's service account to the role giving it access to configmaps, needed to access the jobs' queue that is managed by a cron job not jobman itself
subjects:
- kind: ServiceAccount
  name: jobman-serviceaccount
  namespace: jobman-service
roleRef:
 kind: Role
 name: role-jobman-serviceaccount-configmap
 apiGroup: rbac.authorization.k8s.io
 
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobman-k8s-logger-serviceaccount
  namespace: jobman-service
annotations:
  description: Needed for the k8s-logger sidecar container launched with a job when logs are stored in a file
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: jobman-k8s-logger-serviceaccount-secret
  namespace: jobman-service-exec
  annotations:
    kubernetes.io/service-account.name: jobman-k8s-logger-serviceaccount
annotations:
  description: Predefined token for the service account of the k8s-logger sidecar container,  to be mounted manually in the sidecar
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-jobman-k8s-logger-serviceaccount
  namespace: jobman-service-exec
annotations:
  description: Rights needed by the k8s-logger sidecar container of every job
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-jobman-k8s-logger-serviceaccount
  namespace: jobman-service-exec
annotations:
  description: Binds the roles needed by the k8s-logger sidecar to its service account
subjects:
- kind: ServiceAccount
  name: jobman-k8s-logger-serviceaccount
  namespace: jobman-service
roleRef:
 kind: Role
 name: role-jobman-k8s-logger-serviceaccount
 apiGroup: rbac.authorization.k8s.io
 
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: webservice-config
  namespace: jobman-service
data:
  settings.json: |
    {
      "jobsQueue": {
          "namespace": "jobman-service",
          "configmap": "jobman-queue-position",
          "gpuResources": [
              "nvidia.com/gpu"
          ]
      },
      "job": {
          "serviceAccount": "jobman-k8s-logger-serviceaccount",
          "serviceAccountTokenSecret": "jobman-k8s-logger-serviceaccount-secret",
          "kubeRootCASecret": "kube-root-ca.crt",
          "userNameAnnotation": "chaimeleon.eu/userName",
          "protectedNamespace": "jobman-service-exec",
          "annotationDatasetsList": "chaimeleon.eu/datasetsIDs",
          "annotations": [
              {
                  "key": "chaimeleon.eu/persistentHomeMountPoint",
                  "value": "/home/chaimeleon/persistent-home",
                  "valueType": "string"
              },

              {
                  "key": "chaimeleon.eu/persistentSharedFolderMountPoint",
                  "value": "/home/chaimeleon/persistent-shared-folder",
                  "valueType": "string"
              },
              {
                  "key": "chaimeleon.eu/datasetsMountPoint",
                  "value": "/home/chaimeleon/datasets",
                  "valueType": "string"
              }

          ],
          "defaultImage": "harbor.chaimeleon-eu.i3m.upv.es:5000/chaimeleon-library-batch/ubuntu-python:latest",
          "defaultImageReference": {
            "registry": "harbor.chaimeleon-eu.i3m.upv.es:5000",
            "organization": "chaimeleon-library-batch",
            "name": "ubuntu-python",
            "tag": "latest",
            "digest": null
          },
          "userConfigmap": "chaimeleon",
          "priorityClassName":"processing-applications",
          "securityContext": {
            "runAsUser": 1000,
            "runAsGroup": 1000,
            "fsGroup": 1000,
            "supplementalGroups": []
          },
          "resources": {
            "default": "no-gpu",
            "label": "chaimeleon.eu/jobResourcesFlavor",
            "predefined": [
                {
                    "name": "small-gpu",
                    "description": "",
                    "maxRunTime": 16,
                    "resources": {
                        "requests": {
                            "cpu": "3000m",
                            "memory": "28G",
                            "nvidia.com/gpu": 1
                        },
                        "limits": {
                            "cpu": "6000m",
                            "memory": "28G",
                            "nvidia.com/gpu": 1
                        }
                    }
                },
                {
                    "name": "medium-gpu",
                    "description": "",
                    "maxRunTime": 24,
                    "resources": {
                        "requests": {
                            "cpu": "7000m",
                            "memory": "60G",
                            "nvidia.com/gpu": 1
                        },
                        "limits": {
                            "cpu": "8000m",
                            "memory": "60G",
                            "nvidia.com/gpu": 1
                        }
                    }
                },
                {
                    "name": "large-gpu",
                    "description": "",
                    "maxRunTime": 24,
                    "resources": {
                        "requests": {
                            "cpu": "7000m",
                            "memory": "60G",
                            "nvidia.com/gpu": 1
                        },
                        "limits": {
                            "cpu": "8000m",
                            "memory": "60G",
                            "nvidia.com/gpu": 1
                        }
                    }
                },
                {
                    "name": "no-gpu",
                    "description": "",
                    "maxRunTime": 8,
                    "resources": {
                        "requests": {
                            "cpu": "7000m",
                            "memory": "60G"
                        },
                        "limits": {
                            "cpu": "8000m",
                            "memory": "60G"
                        }
                    }
                }
            ]
          },
        "k8sLogger": {
            "image": "jobman-k8s-logger:2.1.1",
            "sleep": 15
        }
      },
      "kubeConfig": {
          "type": "cluster",
          "file": null
      },
      "harborProjects": [
              {
                  "name": "chaimeleon-library-batch",
                  "token": null,
                  "baseUrl": "https://harbor.chaimeleon-eu.i3m.upv.es:5000"
              }
          ],
      "oidc": {
          "apiTokenAttributeName": "jobman_service_api_token",
          "url": "https://chaimeleon-eu.i3m.upv.es/auth",
          "realm": "CHAIMELEON",
          "clientId": "jobman-service",
          "clientSecret": ""
      },
      "port": 8080,
      "path": {
          "prefix": "/jobman-service",
          "api": "/api/v1"
      },
      "defaultKubeURL": "https://chaimeleon-eu.i3m.upv.es/"
    }



  
---
    
apiVersion: v1
kind: Service
metadata:
  name: jobman-service
  namespace: jobman-service
spec:
  ports:
  - port: 8080
    target: 8080
    protocol: TCP
    name: api
  selector:
    app: jobman-service-deployment
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobman-service-deployment
  namespace: jobman-service
spec:
  selector:
    matchLabels:
      app: jobman-service-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobman-service-deployment
    spec:
      replicas: 1
      priorityClassName: core-services
      nodeSelector:
        chaimeleon.eu/target: core-services
      serviceAccountName: jobman-serviceaccount
      containers:
      - image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/jobman-service:2.0.0-BETA
        imagePullPolicy: Always
        name: jobman-service-deployment-container
        env:
        - name: SETTINGS_FILE
          value: /opt/jobman/settings.json
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        ports:
        - containerPort: 8080
          name: api
        volumeMounts:
        - name: webservice-configmap
          mountPath: /opt/jobman/settings.json
          subPath: settings.json
      volumes:
      - name: webservice-configmap
        configMap:
          name: webservice-config

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jobman-ingress
  namespace: jobman-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - host: <jobman_host>
      http:
        paths:
          - path: /jobman-service/
            pathType: Prefix
            backend:
              service:
                name: jobman-service
                port:
                  number: 8080