---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/hostpath-provisioner/clinical-data-sql-db/postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  storageClassName: ""
  volumeName: pv-postgresql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
