priorityClassName: core-services
nodeSelector:
  chaimeleon.eu/target: core-services
serviceAccount:
  annotations: {}
  name: ''
rbac:
  role:
    name: dsws-operator-namespaced
  clusterRole:
    name: dsws-operator-cluster
  roleBinding:
    name: dsws-operator-rolebinding-namespaced
  clusterRoleBinding:
    name: dsws-operator-rolebinding-cluster
operatorConfiguration:
  auth:
    url: https://mininode.imaging.i3m.upv.es/auth/realms/EUCAIM-NODE/protocol/openid-connect/token
    client_id: kubernetes-operator
    client_secret: ugVKIjwNQFwajethJsRDQ3Vf2FUx9P8W
    max_retries: 10
  dataset_service:
    url: http://dataset-service-backend-service.dataset-service.svc.cluster.local:11000/
    test_url: ''
    max_retries: 10
  guacamole:
    url: https://mininode.imaging.i3m.upv.es/guacamole/
    user: service-account-kubernetes-operator
    password: XXXXXXXXXXXXXXXX
    connections_creation:
      backend_host: guacamole-guacd.guacamole.svc.cluster.local
      vnc_port: '5900'
      sftp_default_username: ds
      sftp_port: '2222'
  k8s:
    user_prefix: 'oidc:'
    admins_group: oidc:cloud-services-and-security-management
    namespace_prefix: user-
    jobman_service_execution_namespace: jobman-service-exec
    volumes:
      type: "hostPath"
      user_prefix: eucaim-user--
      jobman_service_execution_user: jobman-service-exec
      datasets_path: /tmp/hostpath-provisioner/dataset-service/datasets
      persistent_homes_path: /tmp/hostpath-provisioner/data/homes/users
      persistent_shared_folder_path: /tmp/hostpath-provisioner/data/homes/shared-folder
    checks:
      allowed_repo: harbor.eucaim-node.i3m.upv.es
      not_allowed_repo_message: The image must be one of our internal repository 'harbor.eucaim-node.i3m.upv.es'.
      allowed_images_for_deployment: []
      not_allowed_image_for_deployment_message: ''
      allowed_users_to_deploy: []
      not_allowed_users_to_deploy_message: ''
      max_num_pods_per_user: 0
    openchallenge:
      datasets: []
      nfs_path: ''
      nfs_server: ''
    resource_flavors:
      jobs:
        flavors:
          - name: "small-gpu"
            resources: { target_node: "small-gpu", cpu: "3", max_cpu: "6", memory_gb: 28,  gpu: true }
          - name: "medium-gpu"
            resources: { target_node: "medium-gpu", cpu: "7", max_cpu: "8", memory_gb: 60,  gpu: true }
          - name: "large-gpu"
            resources: { target_node: "large-gpu", cpu: "7", max_cpu: "8", memory_gb: 60,  gpu: true }
          - name: "no-gpu"
            resources: { target_node: "no-gpu", cpu: "7", max_cpu: "8", memory_gb: 60,  gpu: false }
        default_flavor_name: "medium-gpu"
      deployments:
        flavors:
          - name: "desktop"
            tool_match: "desktop-tensorflow|desktop-pytorch|jupyter-tensorflow|jupyter-pytorch"
            resources: { target_node: "desktops",  cpu: "900m",  max_cpu: "2",  memory_gb: 7,  gpu: false }
          - name: "app-service-cpu300"
            tool_match: "nifi"
            name_match: "nifi-nifi"
            # nifi has 4 deployments, the nifi-nifi needs more cpu
            resources: { target_node: "desktops",  cpu: "300m",  max_cpu: "1",  memory_gb: 2,  gpu: false }
          - name: "app-service-cpu200"
            tool_match: "analytic-engine"
            name_match: "ai-layer-ws|ai-layer-trino"
            # analytical-engine has 7 deployments, the ws and trino needs more cpu
            resources: { target_node: "desktops",  cpu: "200m",  max_cpu: "1",  memory_gb: 1,  gpu: false }
          - name: "app-service-cpu100"
            tool_match: "analytic-engine|nifi"
            resources: { target_node: "desktops",  cpu: "100m",  max_cpu: "500m",  memory_gb: 1,  gpu: false }
          - name: "app-service-cpu400"
            tool_match: "chaimeleon-superset"
            # superset has 1 deployment with 2 containers
            resources: { target_node: "desktops",  cpu: "400m",  max_cpu: "1",  memory_gb: 3,  gpu: false }
          - name: "other"
            # This entry at the end match anything and assigns the minimum resources to any unknown deployment.
            tool_match: ".*"
            resources: { target_node: "desktops",  cpu: "100m",  max_cpu: "200m",  memory_gb: 1,  gpu: false }
service:
  type: ClusterIP
  port: 443
image:
  repository: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/k8s-operator
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources:
  requests:
    cpu: 1000m
    memory: 1000Mi
  limits:
    cpu: 1000m
    memory: 1000Mi
