expose:
  type: ingress
  tls: 
    enabled: true
    certSource: secret
    secret:
      secretName: harbor.eucaim-node.i3m.upv.es
  ingress:
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      # This is to disable the uploads in 2 steps. 
      # When it is 'on' (default), there is a first step when the layer of image is uploaded entirely to a buffer in the proxy 
      # and then in a 2nd step the content of buffer is transfered to the destination pod.
      nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
    hosts:
      core: harbor.eucaim-node.i3m.upv.es

# The external URL for Harbor core service. It is used to
# 1) populate the docker/helm commands showed on portal
# 2) populate the token service URL returned to docker client
externalURL: https://harbor.eucaim-node.i3m.upv.es

persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        existingClaim: harbor-harbor-pvc
        subPath: registry
      jobservice:
        jobLog:
          existingClaim: harbor-harbor-pvc
          subPath: jobservice
      database:
        existingClaim: harbor-harbor-pvc
        subPath: database
      redis:
        existingClaim: harbor-harbor-pvc
        subPath: redis
      trivy:
        existingClaim: harbor-harbor-pvc
        subPath: trivy

harborAdminPassword: XXXXXXXXXXXXXXXXX

# The internal TLS used for harbor components secure communicating. In order to enable https
# in each component tls cert files need to provided in advance.
internalTLS:
  enabled: true
  certSource: auto

metrics:
  enabled: false
  
# If service exposed via "ingress", the Nginx will not be used
#nginx:
# nodeSelector:
#   chaimeleon.eu/target: core-services
# priorityClassName: core-services
# resources:
#   requests:
#     memory: "1000Mi"
#     cpu: "1000m"
#   limits:
#     memory: "1000Mi"
#     cpu: "1000m" #1 Gb

portal:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "1000m" #1 cpu
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-services

core:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "1000m" #1 cpu
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-services

jobservice:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "1000m" #1 cpu
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-services

registry:
  registry:
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1024Mi"
        cpu: "1000m" #1 cpu
  controller:
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1024Mi"
        cpu: "1000m" #1 cpu
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-services
  credentials:
    username: admin
    password: XXXXXXXXXXX
    # The documentation says that htpasswd excludes username and password, but it is not true, 
    # they are used anyway to configure the "core" service, so if you don't set them, the default values will be used 
    # and will not match with the htpasswd used to configure the "registry" service and so the CLI login (docker login) will fail.
    # Conclusion: you should ADDITIONALLY set the htpasswd only if you have to integrate with tools like argocd or flux,
    #             just mantain the same and not regenerate the salt every time the chart template is rendered.
    #             It can be generated (for admin and some-password) with: apt install apache2-utils && htpasswd -nbBC10 admin some-password
    #htpasswdString: admin:XXXXXXXXXXXXXX

trivy:
  enabled: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "1000m" #1 cpu
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-services

database:
  type: internal
  internal:
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1024Mi"
        cpu: "1000m" #1 cpu
    nodeSelector:
      chaimeleon.eu/target: core-services
    priorityClassName: core-services
    password: XXXXXXXXXXXXXXXXX

redis:
  type: internal
  internal:
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1024Mi"
        cpu: "1000m" #1 cpu
    nodeSelector:
      chaimeleon.eu/target: core-services
    priorityClassName: core-services

exporter:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "1000m" #1 cpu
  nodeSelector:
    chaimeleon.eu/target: core-services
  priorityClassName: core-services

