
parent=keycloak
# parent=keycloak.v2    
#     v2 is functional and working good but the styles still requires few adjustments: 
#     in the register form, attribute groups are not well visible as sections, the title is not well padded and remarked
import=common/eucaim-node



