kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: package-repos-proxy-pvc
  namespace: package-repos-proxy
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi