apiVersion: v1
kind: Service
metadata:
  name: package-repos-proxy
  namespace: package-repos-proxy
spec:
  ports:
  - port: 80
    protocol: TCP
    name: api
  selector:
    app: package-repos-proxy