apiVersion: v1
kind: ServiceAccount
metadata:
  name: iblanque-account
  namespace: chaimeleon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serlophug-account
  namespace: chaimeleon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dquilis-account
  namespace: chaimeleon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: palollo-account
  namespace: chaimeleon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asalic-account
  namespace: chaimeleon
