apiVersion: v1
kind: Pod
metadata:
  name: prepare-postgresql-pvc
  namespace: kubeapps 
spec:
  restartPolicy: Never
  volumes:
    - name: database-data-volume
      persistentVolumeClaim:
        claimName: data-kubeapps-postgresql-0
  containers:
  - name: prepare-postgresql-pvc
    image: busybox
#   image: docker.io/bitnami/postgresql:11.12.0-debian-10-r5
    securityContext:
      runAsUser: 0
    command: ['sh', '-c', 'chown -R 1001:1001 /bitnami/postgresql']
#   command: ['sh', '-c', 'tail -f /dev/null']
    volumeMounts:
      - name: database-data-volume
        mountPath: /bitnami/postgresql
