apiVersion: "v1"
kind: "Policy"
metadata:
  name: "k8s_chaimeleon_users"
spec: 
  description: |
    Policy for chaimeleon users that can access to the Kubernetes.
  action_list: 
    - "chaimeleon_crb_users"
    - "chaimeleon_rb_users"
    - "chaimeleon_kyverno_policies"
    - "chaimeleon_own_configmap"
    - "chaimeleon_ceph_config"
