apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-users
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 25Gi
    requests.storage: 25Gi
    limits.cpu: "6"
    limits.memory: 50Gi
    requests.nvidia.com/gpu: 2
