apiVersion: "v1"
kind: "Action"
metadata:
  name: "chaimeleon_ceph_config"
spec: 
  description: |
    Create the user home directory, the ceph user and the k8s secret that contains the ceph key.
  allow_yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: allow-ceph-config-__TENANT_USERNAME__
      namespace: kube-authorizer
    spec:
      template:
        spec:
          volumes:
            - name: cephs-volume
              cephfs:
                monitors:
                  - 192.168.3.30:6789
                  - 192.168.3.24:6789
                  - 192.168.3.5:6789
                  - 192.168.3.16:6789
                path: /homes/chaimeleon-users
                user: chaimeleon-user-creator
                secretRef:
                  name: ceph-auth
          containers:
          - name: deny-rbac
            image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/user-creation:test
            imagePullPolicy: Always
            command: ["/bin/bash"]
            args: ["-c", "/home/ubuntu/create_ceph_home_user.sh"]
            volumeMounts:
              - name: cephs-volume
                mountPath: /mnt/cephfs
            env:
            - name: TENANT_TYPE
              value: "__TENANT_TYPE__"
            - name: TENANT_NAMESPACE
              value: "__TENANT_NAMESPACE__"
            - name: TENANT_NAME
              value: "__TENANT_USERNAME__"
            - name: K8S_TOKEN
              value: "d2KLKJfg35a52gvSffth56h2ol23df63cUSh1k5u23aq85rt1+rt56d+"
            - name: K8S_ENDPOINT
              value: "https://192.168.3.13:6443"
            - name: KEYCLOAK_ENDPOINT
              value: "https://chaimeleon-test.grycap.i3m.upv.es"
            - name: KEYCLOAK_REALM
              value: "CHAIMELEON"
            - name: DATASET_SERVICE_ENDPOINT
              value: "http://dataset-service-backend-service.dataset-service.svc.cluster.local:11000"
            - name: KEYCLOAK_CLIENT
              value: "kubeauthorizer-pod"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "a3401596-088b-476e-92d8-a486f42e0406"
            - name: MOUNTED_DIR_PERSISTENT_HOMES
              value: "/mnt/cephfs"
            - name: DIR_PERSISTENT_SHARED
              value: "/homes/chaimeleon-shared-folder"   
            - name: DIR_PERSISTENT_HOMES
              value: "/homes/chaimeleon-users"   
            - name: DIR_DATASETS
              value: "/datasets"   
            - name: DIR_DATA
              value: "/datalake"   
            - name: CEPH_HOST
              value: "192.168.3.16"
            - name: CEPH_FS_VOL_NAME
              value: "data"     
            - name: CEPH_PREFIX_ACCOUNT
              value: "chaimeleon"       
            - name: CEPH_ADMIN_USER #ceph auth get-or-create client.chaimeleon-user-creator mon "allow * fsname=data" mds "allow * fsname=data" osd "allow * tag cephfs data=data"
              value: "chaimeleon-user-creator"
            - name: CEPH_ADMIN_KEY
              value: "AQB7e1JjEhsdERAA8ANlX7gjtC/nUJUIuF9SPA=="                                   
          restartPolicy: Never
      backoffLimit: 4

  deny_yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: deny-ceph-config-__TENANT_USERNAME__
      namespace: kube-authorizer
    spec:
      template:
        spec:
          containers:
          - name: deny-rbac
            image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/user-creation:test
            imagePullPolicy: Always
            command: ["/bin/bash"]
            args: ["-c", "/home/ubuntu/unauthorise_ceph_user_home.sh"]
            env:
            - name: TENANT_TYPE
              value: "__TENANT_TYPE__"
            - name: TENANT_NAMESPACE
              value: "__TENANT_NAMESPACE__"
            - name: TENANT_NAME
              value: "__TENANT_USERNAME__"
            - name: K8S_TOKEN
              value: "d2KLKJfg35a52gvSffth56h2ol23df63cUSh1k5u23aq85rt1+rt56d+"
            - name: K8S_ENDPOINT
              value: "https://192.168.3.13:6443"
            - name: CEPH_PREFIX_ACCOUNT
              value: "chaimeleon"      
            - name: CEPH_HOST
              value: "192.168.3.16"          
            - name: MOUNTED_DIR_PERSISTENT_HOMES
              value: "/mnt/cephfs"                           
          restartPolicy: Never
      backoffLimit: 4
