apiVersion: "v1"
kind: "Action"
metadata:
  name: "chaimeleon_kyverno_policies"
spec: 
  description: |
    Kyverno ClusterPolicies:
      - Ingress path -> Allow create ingress objects only if the root path is the namespace of the tenant.
      - Security context -> Allow use onky an specific GID
  allow_yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: allow-kyverno-policies-__TENANT_USERNAME__
      namespace: kube-authorizer
    spec:
      template:
        spec:
          containers:
          - name: deny-rbac
            image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/user-creation:test
            imagePullPolicy: Always
            command: ["/bin/bash"]
            args: ["-c", "/home/ubuntu/create_kyverno_policies.sh"]
            env:
            - name: TENANT_TYPE
              value: "__TENANT_TYPE__"
            - name: TENANT_NAMESPACE
              value: "__TENANT_NAMESPACE__"
            - name: TENANT_NAME
              value: "__TENANT_USERNAME__"
            - name: K8S_TOKEN
              value: "d2KLKJfg35a52gvSffth56h2ol23df63cUSh1k5u23aq85rt1+rt56d+"
            - name: K8S_ENDPOINT
              value: "https://192.168.3.13:6443"
            - name: KEYCLOAK_ENDPOINT
              value: "https://chaimeleon-test.grycap.i3m.upv.es"
            - name: KEYCLOAK_REALM
              value: "CHAIMELEON"
            - name: DATASET_SERVICE_ENDPOINT
              value: "http://dataset-service-backend-service.dataset-service.svc.cluster.local:11000"
            - name: KEYCLOAK_CLIENT
              value: "kubeauthorizer-pod"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "a3401596-088b-476e-92d8-a486f42e0406"
                                      
          restartPolicy: Never
      backoffLimit: 4

  deny_yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: deny-kyverno-policies-__TENANT_USERNAME__
      namespace: kube-authorizer
    spec:
      template:
        spec:
          containers:
          - name: deny-rbac
            image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/user-creation:test
            imagePullPolicy: Always
            command: ["/bin/bash"]
            args: ["-c", "python3 /home/ubuntu/delete_kyverno_policy.py $$K8S_ENDPOINT $$K8S_TOKEN $$KUBE_AUTH_TENANT_TYPE oidc:$$KUBE_AUTH_TENANT_USERNAME ingress-subpath; python3 /home/ubuntu/delete_kyverno_policy.py $$K8S_ENDPOINT $$K8S_TOKEN $$KUBE_AUTH_TENANT_TYPE oidc:$$KUBE_AUTH_TENANT_USERNAME security-context-gid"]
            env:
            - name: KUBE_AUTH_TENANT_EMAIL
              value: "__TENANT_EMAIL__"
            - name: KUBE_AUTH_TENANT_EXTERNAL_ID
              value: "__TENANT_EXTERNAL_ID__"
            - name: KUBE_AUTH_TENANT_TYPE
              value: "__TENANT_TYPE__"
            - name: KUBE_AUTH_TENANT_NAMESPACE
              value: "__TENANT_NAMESPACE__"
            - name: KUBE_AUTH_TENANT_USERNAME
              value: "__TENANT_USERNAME__"
            - name: KUBE_AUTH_ACTION_NAME
              value: "__ACTION_NAME__"
            - name: KUBE_AUTH_POLICY_NAME
              value: "__POLICY_NAME__"
            - name: K8S_TOKEN
              value: "d2KLKJfg35a52gvSffth56h2ol23df63cUSh1k5u23aq85rt1+rt56d+"
            - name: K8S_ENDPOINT
              value: "https://192.168.3.13:6443"
          restartPolicy: Never
      backoffLimit: 4
