apiVersion: "v1"
kind: "Action"
metadata:
  name: "chaimeleon_rb_users"
spec: 
  description: "RoleBinding (Namespace) - chaimeleon-users-role-namespace"
  allow_yaml: |
    kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: chaimeleon-users-__TENANT_USERNAME__
      namespace: __TENANT_NAMESPACE__
    subjects:
    - kind: User
      name: "oidc:__TENANT_USERNAME__"
    roleRef:
      kind: ClusterRole
      name: chaimeleon-users-role-namespace
      apiGroup: rbac.authorization.k8s.io

  deny_yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: deny-__TENANT_USERNAME__-rb
      namespace: kube-authorizer
    spec:
      template:
        spec:
          containers:
          - name: deny-rbac
            image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/user-creation:test
            imagePullPolicy: Always
            command: ["/bin/bash"]
            args: ["-c", "python3 /home/ubuntu/delete_rolebinding.py $$K8S_ENDPOINT $$K8S_TOKEN  $$KUBE_AUTH_TENANT_TYPE oidc:$$KUBE_AUTH_TENANT_USERNAME $$KUBE_AUTH_TENANT_NAMESPACE chaimeleon-users-role-namespace"]
            env:
            - name: KUBE_AUTH_TENANT_EMAIL
              value: "__TENANT_EMAIL__"
            - name: KUBE_AUTH_TENANT_EXTERNAL_ID
              value: "__TENANT_EXTERNAL_ID__"
            - name: KUBE_AUTH_TENANT_TYPE
              value: "__TENANT_TYPE__"
            - name: KUBE_AUTH_TENANT_NAMESPACE
              value: "__TENANT_NAMESPACE__"
            - name: KUBE_AUTH_TENANT_USERNAME
              value: "__TENANT_USERNAME__"
            - name: KUBE_AUTH_ACTION_NAME
              value: "__ACTION_NAME__"
            - name: KUBE_AUTH_POLICY_NAME
              value: "__POLICY_NAME__"
            - name: K8S_TOKEN
              value: "d2KLKJfg35a52gvSffth56h2ol23df63cUSh1k5u23aq85rt1+rt56d+"
            - name: K8S_ENDPOINT
              value: "https://192.168.3.13:6443"
          restartPolicy: Never
      backoffLimit: 4
